#!/usr/bin/env python3
"""
Playlist Folder Sync — Rebuild playlist folders from Apple Music M3U exports.

Reads .m3u files exported from Apple Music, matches each track to your local
MP3 library by metadata (Title + Artist), and creates numbered folders:

    Playlist Folders/
    ├── Driving/
    │   ├── 01-Light's Theme.mp3      (symlink or copy)
    │   ├── 02-Bury The Light.mp3
    │   └── 03-Sonne.mp3
    └── Workout/
        ├── 01-Rip & Tear.mp3
        └── 02-DOOM Eternal.mp3

The script is fully idempotent — run it after updating your M3U exports and
it will add, remove, rename, and reorder files to match the current playlists.

Directory Layout (inside iTunes):
    ~/Music/iTunes/
    ├── Playlist Exports/           Drop your .m3u files here
    │   ├── Driving.m3u
    │   ├── Workout.m3u
    │   └── Chill.m3u
    └── Playlist Folders/           Generated by this script
        ├── Driving/
        ├── Workout/
        └── Chill/

Dependencies:
    pip install mutagen

Usage:
    # Preview what would change (default: dry-run)
    python3 sync_playlists.py

    # Actually create / update playlist folders with symlinks
    python3 sync_playlists.py --apply

    # Use file copies instead of symlinks (for devices without symlink support)
    python3 sync_playlists.py --apply --copy

    # Custom paths
    python3 sync_playlists.py --apply \
        --exports-dir /path/to/m3us \
        --output-dir /path/to/output \
        --library-dir /path/to/mp3s
"""

import os
import re
import sys
import shutil
import argparse
from pathlib import Path
from typing import Optional, List, Tuple, Dict
from difflib import SequenceMatcher

from mutagen.mp3 import MP3

DEFAULT_EXPORTS_DIR = Path("/mnt/c/Users/david/Music/iTunes/Playlist Exports")
DEFAULT_OUTPUT_DIR = Path("/mnt/d/3-Music")
DEFAULT_LIBRARY_DIR = Path("/mnt/c/Users/david/iCloudDrive/1-Storage/1-Libraries/3-Music")

MATCH_THRESHOLD = 0.75


def parse_m3u(m3u_path: Path) -> List[Tuple[str, str]]:
    """Parse an M3U playlist and return a list of (artist, title) tuples."""
    tracks = []
    with open(m3u_path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        line = line.strip()
        if line.startswith("#EXTINF:"):
            meta = line.split(",", 1)
            if len(meta) < 2:
                continue
            track_info = meta[1].strip()

            if " - " in track_info:
                artist, title = track_info.split(" - ", 1)
                artist = artist.strip()
                title = title.strip()
            else:
                artist = ""
                title = track_info

            tracks.append((artist, title))

    return tracks


def build_library_index(library_dir: Path) -> Dict[str, List[Path]]:
    """Scan the local MP3 library and build an index keyed by artist|title."""
    index: Dict[str, List[Path]] = {}
    print(f"  Indexing library: {library_dir}")

    mp3_files = list(library_dir.rglob("*.mp3"))
    for mp3_path in mp3_files:
        try:
            audio = MP3(str(mp3_path))
            artist = str(audio.tags.get("TPE1", "")) if audio.tags else ""
            title = str(audio.tags.get("TIT2", "")) if audio.tags else ""

            key = f"{artist.lower()}|{title.lower()}"
            index.setdefault(key, []).append(mp3_path)
        except Exception:
            continue

    print(f"  Indexed {len(mp3_files)} MP3s")
    return index


def fuzzy_ratio(a: str, b: str) -> float:
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()


def find_best_match(artist: str, title: str, index: Dict[str, List[Path]]) -> Optional[Path]:
    """Find the best matching MP3 in the library for the given artist/title."""
    search_key = f"{artist.lower()}|{title.lower()}"

    if search_key in index:
        return index[search_key][0]

    best_path = None
    best_score = 0.0

    for key, paths in index.items():
        parts = key.split("|", 1)
        if len(parts) < 2:
            continue
        lib_artist, lib_title = parts

        artist_score = fuzzy_ratio(artist, lib_artist) if artist else 0.5
        title_score = fuzzy_ratio(title, lib_title) if title else 0.5
        score = (title_score * 0.7) + (artist_score * 0.3)

        if score > best_score and score >= MATCH_THRESHOLD:
            best_score = score
            best_path = paths[0]

    return best_path


def sanitize_filename(name: str) -> str:
    illegal = '<>:"/\\|?*'
    for ch in illegal:
        name = name.replace(ch, "-")
    return name.strip(". ")


def sync_playlist(
    playlist_name: str,
    tracks: List[Tuple[str, str]],
    index: Dict[str, List[Path]],
    output_dir: Path,
    use_copy: bool,
    dry_run: bool,
) -> dict:
    """Create or update a single playlist folder. Returns a report dict."""
    playlist_dir = output_dir / sanitize_filename(playlist_name)

    report = {
        "playlist": playlist_name,
        "dir": str(playlist_dir),
        "matched": 0,
        "unmatched": [],
        "removed": 0,
        "created": 0,
    }

    current_files: Dict[str, Path] = {}
    if playlist_dir.exists():
        for f in playlist_dir.iterdir():
            if f.is_file() or f.is_symlink():
                current_files[f.name] = f

    new_files: set = set()

    for i, (artist, title) in enumerate(tracks, start=1):
        match_path = find_best_match(artist, title, index)
        num = str(i).zfill(2)

        if match_path:
            ext = match_path.suffix
            safe_title = sanitize_filename(title) or "Unknown"
            new_name = f"{num}-{safe_title}{ext}"
            new_files.add(new_name)

            dest_path = playlist_dir / new_name

            if dry_run:
                if not dest_path.exists():
                    report["created"] += 1
            else:
                playlist_dir.mkdir(parents=True, exist_ok=True)

                if dest_path.exists() or dest_path.is_symlink():
                    real_dest = dest_path.resolve()
                    if real_dest != match_path.resolve():
                        if dest_path.is_symlink() or dest_path.is_file():
                            dest_path.unlink()

                if not dest_path.exists():
                    if use_copy:
                        shutil.copy2(str(match_path), str(dest_path))
                    else:
                        try:
                            rel = os.path.relpath(str(match_path), str(playlist_dir))
                        except ValueError:
                            rel = str(match_path)
                        dest_path.symlink_to(rel)
                    report["created"] += 1

            report["matched"] += 1
        else:
            report["unmatched"].append(f"{num}- {artist} - {title}")

    for old_name, old_path in current_files.items():
        if old_name not in new_files:
            if dry_run:
                report["removed"] += 1
            else:
                old_path.unlink()
                report["removed"] += 1

    if not dry_run and playlist_dir.exists() and not any(playlist_dir.iterdir()):
        playlist_dir.rmdir()

    return report


def main():
    parser = argparse.ArgumentParser(
        description="Sync Apple Music M3U playlists to numbered folder structures"
    )
    parser.add_argument(
        "--apply", action="store_true", help="Actually create/update folders (default: dry-run)"
    )
    parser.add_argument(
        "--symlink", action="store_true", help="Use symlinks instead of copying files"
    )
    parser.add_argument(
        "--exports-dir", type=Path, default=DEFAULT_EXPORTS_DIR, help="Directory containing .m3u files"
    )
    parser.add_argument(
        "--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Directory for generated playlist folders"
    )
    parser.add_argument(
        "--library-dir", type=Path, default=DEFAULT_LIBRARY_DIR, help="Root of your local MP3 library"
    )
    args = parser.parse_args()

    dry_run = not args.apply
    mode = "DRY RUN" if dry_run else "APPLY"

    if not args.exports_dir.exists():
        print(f"Exports directory not found: {args.exports_dir}")
        print("Create it and drop your .m3u files there.")
        sys.exit(1)

    m3u_files = sorted(args.exports_dir.glob("*.m3u"))
    if not m3u_files:
        print(f"No .m3u files found in: {args.exports_dir}")
        sys.exit(0)

    print(f"\n{'='*70}")
    print(f"  Playlist Folder Sync — {mode}")
    print(f"  Exports:  {args.exports_dir}")
    print(f"  Output:   {args.output_dir}")
    print(f"  Library:  {args.library_dir}")
    print(f"  Method:   {'Symlink' if args.symlink else 'Copy'}")
    print(f"  Playlists: {len(m3u_files)}")
    print(f"{'='*70}\n")

    index = build_library_index(args.library_dir)

    total_matched = 0
    total_unmatched = 0
    total_created = 0
    total_removed = 0

    for m3u_path in m3u_files:
        playlist_name = m3u_path.stem
        tracks = parse_m3u(m3u_path)
        print(f"  [{playlist_name}]  {len(tracks)} tracks")

        report = sync_playlist(
            playlist_name=playlist_name,
            tracks=tracks,
            index=index,
            output_dir=args.output_dir,
            use_copy=not args.symlink,
            dry_run=dry_run,
        )

        total_matched += report["matched"]
        total_unmatched += len(report["unmatched"])
        total_created += report["created"]
        total_removed += report["removed"]

        if report["unmatched"]:
            print(f"    ⚠ Unmatched ({len(report['unmatched'])}):")
            for u in report["unmatched"][:5]:
                print(f"       {u}")
            if len(report["unmatched"]) > 5:
                print(f"       ... and {len(report['unmatched']) - 5} more")

    print(f"\n{'='*70}")
    print(f"  Summary")
    print(f"{'='*70}")
    print(f"  Matched:   {total_matched}")
    print(f"  Unmatched: {total_unmatched}")
    print(f"  Created:   {total_created}")
    print(f"  Removed:   {total_removed}")

    if dry_run:
        print(f"\n  This was a DRY RUN. No files were modified.")
        print(f"  Run with --apply to create/update folders.")
    print(f"{'='*70}\n")


if __name__ == "__main__":
    main()
